---
title: "KNN Model for Cumulative Data"
author: "Lyndsey Umsted"
date: "2022-10-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading necessary libraries
```{r}
#install.packages("kknn")
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(corrplot)
library(ggthemes)
tidymodels_prefer()
library(kknn)
```

Splitting into training and testing
```{r}
setwd("C:/Users/18586/Desktop/PSTAT 131/PSTAT-131-final-project/models")
load("pandemic_cum.rda")

set.seed(2002)

pandemic_cum <- pandemic_cum %>%
  select(-c("prop", "confirmed_cases", "population", "ID_co", "proplog"))

pandemic_cum_split <- initial_split(pandemic_cum, prop = 0.80, strata = risk)

pandemic_cum_train <- training(pandemic_cum_split)
pandemic_cum_test <- testing(pandemic_cum_split)
```

Creating Recipe:
```{r}
pandemic_cum_rec <- recipe(risk ~ ., data = pandemic_cum_train) %>%
  step_dummy(all_nominal_predictors())
```

KNN Model:
```{r}
knn_model <- nearest_neighbor(
  mode = "classification",
  engine = "kknn", 
  neighbors = 5,
  weight_func = "rectangular", 
  dist_power = NULL
)
```

Workflow:
```{r}
knn_wflow_cum <- workflow() %>% 
  add_model(knn_model) %>% 
  add_recipe(pandemic_cum_rec)
```

Fit KNN model to training data:
```{r}
knn_fit_cum <- fit(knn_wflow_cum, pandemic_cum_train)
```

Generating preicted values for each observation of the training set:
```{r}
pandemic_cum_knn_pred <- predict(knn_fit_cum, new_data = pandemic_cum_train %>% select(-risk))
pandemic_cum_knn_pred %>% 
  head()
```

Attaching a column of the actual observed confirmed cases:
```{r}
pandemic_cum_knn_pred <- bind_cols(pandemic_cum_knn_pred, pandemic_cum_train %>% select(risk))
pandemic_cum_knn_pred %>% 
  head()
```

```{r}
augment(knn_fit_cum, new_data = pandemic_cum_train) %>%
  conf_mat(truth = risk, estimate = .pred_class)
```

```{r}
knn_acc <- augment(knn_fit_cum, new_data = pandemic_cum_train) %>%
  accuracy(truth = risk, estimate = .pred_class)
knn_acc
```

Testing Data:

```{r}
pandemic_cum_knn_pred <- predict(knn_fit_cum, new_data = pandemic_cum_test %>% select(-risk))
pandemic_cum_knn_pred %>% 
  head()
```

Attaching a column of the actual observed confirmed cases:
```{r}
pandemic_cum_knn_pred <- bind_cols(pandemic_cum_knn_pred, pandemic_cum_test %>% select(risk))
pandemic_cum_knn_pred %>% 
  head()
```

```{r}
augment(knn_fit_cum, new_data = pandemic_cum_test) %>%
  conf_mat(truth = risk, estimate = .pred_class)
```

```{r}
knn_acc <- augment(knn_fit_cum, new_data = pandemic_cum_test) %>%
  accuracy(truth = risk, estimate = .pred_class)
knn_acc
```


ROC Curve:
```{r}
roc <- augment(knn_fit_cum, pandemic_cum_test)

roc %>%
  roc_curve(risk, c(.pred_low, .pred_moderate, .pred_high)) %>%
  autoplot()
```


AUC:
```{r}
roc %>%
  roc_auc(risk, c(.pred_low, .pred_moderate, .pred_high))
```



